### PR TITLE
User preferences enabled

### PR DESCRIPTION
**Pull request by kwjolee**
* User preferences table added on AWS
* websocket gateway sends a response back to client when client-side changes are made to preferences or notification status
* `functionName` of some lambda functions are now loosely pre-defined to avoid resource names not being defined yet at deploy time.

Most of the logic regarding adding logs to the dynamo table will eventually migrate to use a queue (SQS), so possible issues there can be disregarded for now.

### CODE REVIEW

**Comment by franceshg** [comment]
when i turn off in-app user preferences, then send a notification, 
1. it hits dynamoLogger lambda
2. log is created in notifications table 
3. it hits activeNotifications lambda - no error
4. does not create an entry in active notifications table
5. does not broadcast (expected since in-app notifications are turned off)

When i log in again to bob with in-app notifications turned off, i get this error in the console: 
Screenshot 2024-11-01 at 2 59 40 PM
Screenshot 2024-11-01 at 2 59 57 PM

And the front-end components don't render. 

When i go in to user preferences table in dynamoDB and manually switch in-app back to true, refresh bobs login, there are no errors, and i do not get the notifications that i sent to bob while in-app notifications were turned off (expected since they are not added to active-notifications table)

So essentially any in-app notifications that are sent to Bob when their in-app notifications are off, are lost. 
In a similar thread, when i turn off in-app then refresh to log back in to Bob I get the above error.

**Comment by kwjolee** [comment]
The error is a frontend sdk issue -- will fix the bug in that repo.

Messages being sent to the user while their notification preference is disabled getting lost is deliberate. If a user has their in app turned off for a long time, and a lot of notifications pile up during that time, we probably don't want that user to get bombarded with a lot of notifications, many of which will be outdated at that point. This can easily be enabled, so I would like other team members to chime in with their thoughts on this design.

**Comment by cshio** [comment]
Yes, discarding notifications if they're disabled in preferences is the intended behavior we previously discussed.  This will apply to all notification types added in the future, as well.

**Comment by franceshg** [comment]
That makes sense and I agree with that decision. When I consider apps that I use and periodically turn off notifications, when I turn notifications back on, it doesn't send me all the ones that I "missed". Great thank you!

**Comment by franceshg** [comment]
great, lgtm!

**Pull request merged**
